name: Test Renovate Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  main:
    name: Run tests
    runs-on: ubuntu-latest
    # Run it only for renovate PRs
    if: |
      startsWith(github.head_ref, 'renovate/') && 
      github.base_ref == 'master'
    steps:
      # Setup Git
      - uses: actions/checkout@v1
        with:
          ref: master
      # Setup Node
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Yarn install
        run: |
          npm install -g yarn
          yarn install

      - name: Run tests
        run: yarn run test
